"""Interfaces abstraites. Les adapters les implémentent."""
from __future__ import annotations
from typing import Protocol, Optional
from .domain import Agence, Volume, Rattachement, Scenario


class AgenceRepository(Protocol):
    def list_franchises(self) -> list[Agence]: ...
    def list_propres(self) -> list[Agence]: ...
    def get(self, code: str) -> Optional[Agence]: ...


class VolumeRepository(Protocol):
    def latest_by_shop(self, shop_id: str) -> Optional[Volume]: ...
    def latest_all(self) -> dict[str, Volume]: ...
    def upsert_snapshot(self, volumes: list[Volume]) -> int: ...


class RattachementRepository(Protocol):
    def by_franchise(self, code: str) -> Optional[Rattachement]: ...
    def all(self) -> dict[str, Rattachement]: ...
    def franchises_of_propre(self, code_propre: str) -> list[str]: ...
    def replace_all(self, rattachements: list[Rattachement]) -> None: ...


class ScenarioRepository(Protocol):
    def save(self, scenario: Scenario) -> None: ...
    def load(self, nom: str) -> Optional[Scenario]: ...
    def list_all(self) -> list[str]: ...


class OsrmClient(Protocol):
    def table(
        self,
        sources: list[tuple[float, float]],
        destinations: list[tuple[float, float]],
    ) -> tuple[list[list[float]], list[list[float]]]:
        """Retourne (distances_m, durees_s) en matrice NxM."""
        ...
